<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class Account extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return false;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'number' => 'required|min:4|max:10',
            'name' => 'required|min:2|max:20',
            'balance_date' => 'required|date',
            'balance' => 'required|numeric',
            'type' => 'required'
        ];
    }

    public function messages()
    {
        //return parent::messages(); // TODO: Change the autogenerated stub
        return [
            'name.required' => '账户名称不得为空！',
            'name.min' => '账户名称不得小于2位！',
            'name.max' => '账户名称不得大于20位！',
            'number.required' => '账户编号不得为空1',
            'number.min' => '账户编号不得小于4位1',
            'number.max' => '账户编号不得大于10位!',
            'balance_date.required' => '余额日期不得为空！',
            'balance_date.data' => '请输入合法日期！',
            'balance.numeric' => '请输入合法数字！',
            'balance.required' => '余额不得为空！'
        ];
    }
}
